### PR TITLE
Update Boulder Features

### PR DESCRIPTION
**Pull request by Jason-Ding19**
Gives the boulders a more variated texture rather than solid stone.
Also adds a chance for coal and iron ores to generate inside larger boulders.

### CODE REVIEW

**Comment by Astrashh** [comment]
These variants should be in their own script so we're not removing the pure stone versions, aside from that lgtm

**Comment by Jason-Ding19** [comment]
k does that work?

**Comment by Astrashh** [comment]
The textured scripts are missing the .tesf extension, add those and I can merge :+1:

**Comment by Jason-Ding19** [comment]
bet

**Pull request merged**
